### ISSUE TITLE
postgres Dockerfile automatically creates insecure credentials

### ISSUE THREAD

**Issue by sazerzac** [mdgriffith/kubernetes-starterkit#1]
It seems postgres' Dockerfile entrypoint](https://github.com/docker-library/postgres/blob/bcfa58b2f0c971ad55f541f3fb868607cd391089/9.6/Dockerfile) calls a script  docker-entrypoint.sh looking for env variables: 

POSTGRES_USER
POSTGRES_PASSWORD

If it can't find them it creates a db user 'postgres' with no password. 

Proposing to change env DB_USER and DB_PASS to above - advantage being no insecure pg user and automatic user creation secrets.

See branch: [https://github.com/mdgriffith/kubernetes-starterkit/compare/bug-postgres_user_creation?expand=1](https://github.com/mdgriffith/kubernetes-starterkit/compare/bug-postgres_user_creation?expand=1)

**Comment by mdgriffith** [comment]
Awesome, merged 👍
